root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "go build -mod=vendor -o ./tmp/sync-svc ./sync-svc/cmd/server/"
  bin = "./tmp/sync-svc"
  full_bin = "source .env && PORT=8003 ./tmp/sync-svc"
  include_dir = ["sync-svc", "shared"]
  exclude_dir = ["tmp", "vendor", "testdata", "listen_stream_admin", "listen_stream_client"]
  include_ext = ["go"]
  exclude_regex = ["_test\\.go"]
  delay = 500
  stop_on_error = true
  rerun = false
  rerun_delay = 500

[log]
  time = true
  main_only = false

[color]
  main = "blue"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
